services:
  - type: web
    name: backend
    env: docker
    plan: free
    repo: https://github.com/leKg1/todo-list
    branch: main
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d1j7fcre5dus73d09ps0-a
      - key: DB_USER
        value: todo_db_ga6e_user
      - key: DB_PASS
        value: 0etNV0pZzOFAtI3RuPr1dubJjiF3aWAk
      - key: DB_NAME
        value: todo_db_ga6e
      - key: DB_PORT
        value: 5432
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: PORT
        value: 4000

  - type: web
    name: frontend
    env: docker
    plan: free
    repo: https://github.com/leKg1/todo-list
    branch: main
    rootDir: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://backend-xxxx.onrender.com