version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: todo
      JWT_SECRET: your_jwt_secret
      PORT: 4000
    ports:
      - '4000:4000'
    profiles: ["prod"]

  frontend:
    build: ../frontend
    depends_on:
      - backend
    ports:
      - '3000:80' # Nginx serves on 80, mapped to host 3000
    profiles: ["prod"]

  backend-dev:
    build: ../backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: todo
      JWT_SECRET: your_jwt_secret
      PORT: 4000
    ports:
      - '4000:4000'
    volumes:
      - ../backend:/app
    command: ["npm", "run", "dev"]
    profiles: ["dev"]

  frontend-dev:
    image: node:20-alpine
    working_dir: /app
    depends_on:
      - backend-dev
    ports:
      - '5173:5173'
    volumes:
      - ../frontend:/app
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "npm install && npm run dev"]
    profiles: ["dev"]

volumes:
  db_data:
